package com.parkingreservation.iuh.demologinmvp.service

import com.parkingreservation.iuh.demologinmvp.model.UserAccessToken
import io.reactivex.Observable
import retrofit2.http.GET
import retrofit2.http.Header
import retrofit2.http.POST
import retrofit2.http.Query

/**
* Created by Kushina on 25/03/2018.
*/

interface LoginService {

    /**
     *  @URL       .../oauth/token?grant_type=password&username={username}&password={unencodeed_password}
     *  @auth      Generated by Base 64 with
     *             Client: "UserApp"
     *             Secret: "UserApp_ParkingReservation"
     *  @pass      password of user
     *  @username  username of User
     */
    @POST("oauth/token?grant_type=password")
    fun signIn(@Header("Authorization") auth: String
               , @Query("username") username: String
               , @Query("password") password: String) : Observable<UserAccessToken>

}